services:
  frontend:
    image: ${DOCKER_IMAGE_FRONTEND:-frontend-local:latest}
    container_name: ng-console
    ports:
      - "80:80"
    volumes:
      - /opt/frontend/config.json:/usr/share/nginx/html/assets/config.json:ro

networks:
  default:
    name: app-network
    external: true
