apiVersion: v1
kind: Namespace
metadata:
  name: ng-console-staging
  labels:
    app.kubernetes.io/name: ng-console-staging
    app.kubernetes.io/part-of: ng-console-platform
    environment: staging
